# Site
name: 'St. Thomas Hospital'
description: 'St. Thomas Hospital & Kinderhilfe.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
disqus: 'demowebsite'
email: 'info@praxis-frauenberg.de'
#mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    marion-fuhrmann:
      name:           Dr. med. Marion Fuhrmann
      site:           https://thomas-hospital.de
      avatar:         assets/images/avatar-marion-fuhrmann.jpg
      bio:            "Vorsitzende, Dokumentation und Reisekoordination, Medizinscher Support."
      email:          info@praxis-frauenberg.de 

    philippe-mbarga:
      name:           Msgr. Dr. Philippe Alain Mbarga
      site:           https://thomas-hospital.de
      avatar:         assets/images/avatar-philippe-mbarga.jpg
      bio:            "Bischof von Ebolowa, Projektleiter in Kamerun"
      email:          mbarga@web.de

    josephina-schaefer:
      name:           Josephina Schäfer
      site:           https://thomas-hospital.de
      avatar:         assets/images/avatar-default-female.png
      bio:            ""
      email:          info@praxis-frauenberg.de 

    petra-leinweber:
      name:           Petra Leinweber
      site:           https://thomas-hospital.de
      avatar:         assets/images/avatar-petra-leinweber.jpg
      bio:            "Vorsitzende, Einrichtung und Beratung Berufsschulzentrum / Hospital und aller weiteren Projekte, Transport und Logistik, Dokumentation und Reisekoordination"
      email:          info@praxis-frauenberg.de 

    leslie-scheuber:
      name:           Leslie Scheuber
      site:           https://thomas-hospital.de
      avatar:         assets/images/avatar-leslie-scheuber.jpg
      bio:            "Website-Einrichtung und Betreuung"
      email:          info@praxis-frauenberg.de 

    sylvia-usbeck:
      name:           Sylvia Usbeck
      site:           https://thomas-hospital.de
      avatar:         assets/images/avatar-sylvia usbeck.jpg
      bio:            "Website-Einrichtung und Betreuung"
      email:          info@praxis-frauenberg.de 

    david-usbeck:
      name:           David Usbeck
      site:           https://thomas-hospital.de
      avatar:         assets/images/avatar-default-male.png
      bio:            "Website-Einrichtung und Betreuung, Englisch-Übersetzung"
      email:          info@praxis-frauenberg.de 

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: marion-fuhrmann
      avatar: /assets/images/avatar-default-male.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]